services:

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb_group4
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '${INFLUXDB_PORT}:${INNER_PORT_INFLUXDB}'
    volumes:
      - influxdb_data:/var/lib/influxdb

  telegraf:
    image: telegraf
    container_name: telegraf_group4
    restart: always
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana-server_group4
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '${GRAFANA_PORT}:${INNER_PORT_GRAFANA}'
    volumes:
      - grafana_data:/var/lib/grafana
      
volumes:
  grafana_data: {}
  influxdb_data: {}
